/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.test.greeting;

import com.android.build.gradle.AppExtension;
import com.android.build.gradle.LibraryExtension;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class GreetingPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a transform to AppExtension
        AppExtension appExtension = project.getExtensions().findByType(AppExtension.class);
        appExtension.registerTransform(new MyTransform());
        //添加依赖
        project.getDependencies().add("implementation","org.javassist:javassist:3.20.0-GA");
        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'com.test.greeting.greeting'"));
        });
        project.getTasks().register("greeting2", task -> {
            task.doLast(s -> System.out.println("Hello2 from plugin 'com.test.greeting.greeting'"));
        });
    }
}
